### ISSUE TITLE
请问这里是不是写错了

### ISSUE THREAD

**Issue by peaceandbeauty** [lujian101/LuaTableOptimizer#4]
![image](https://user-images.githubusercontent.com/53162725/80173100-5e28db00-8621-11ea-8888-7b0c163038ab.png)

**Comment by lujian101** [comment]
好像确实是写错了，谢谢提醒。我目前位置代码从来没有运行到这里来。。。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"zhihexiao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 中午11:48
收件人:&nbsp;"lujian101/LuaTableOptimizer"<LuaTableOptimizer@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[lujian101/LuaTableOptimizer] 请问这里是不是写错了 (#4)
