### ISSUE TITLE
想请问下这里的重写入目的是什么呢

### ISSUE THREAD

**Issue by peaceandbeauty** [lujian101/LuaTableOptimizer#5]
![image](https://user-images.githubusercontent.com/53162725/80369923-a49c6500-88c1-11ea-9c88-db5f6f0befbb.png)

赋值一样，没看明白这个操作的用意

**Comment by lujian101** [comment]
luatable 有点类似引用类型，优化之前每个table都是独立的，当我们进行唯一化之后重新覆盖回去就是为了消除多份内容相同的table

**Comment by peaceandbeauty** [comment]
明白了，谢谢你的回答👍👍
