### ISSUE TITLE
序列化列表的时候，这个排序有问题

### ISSUE THREAD

**Issue by zsmhunter** [lujian101/LuaTableOptimizer#6]
![image](https://user-images.githubusercontent.com/54316882/92464090-43858600-f1ff-11ea-8a94-cedc1c2f54b8.png)
如果key值同时有number跟string的话，sort就会有问题

**Comment by lujian101** [comment]
thank you.

please try:

```lua
table.sort(
        sortedK,
	function( l, r )
		local lt = type( l )
		local rt = type( r )
		if lt ~= rt then
			return lt < rt
		else
			return l < r
		end
	end
)
```

**Comment by zsmhunter** [comment]
个人不建议这么sort。这样lua的排序会出现乱序问题，会报错的，我现在的做法是判断到有类型不同，直接换了个sortfunction
![image](https://user-images.githubusercontent.com/54316882/92469526-89464c80-f207-11ea-8580-a3a06c9fb17c.png)
